kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk
  namespace: my-sonarqube
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-postgres-pvc
  namespace: my-sonarqube
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi